### ISSUE TITLE
Could not find 'bindrcpp'

### ISSUE THREAD

**Issue by ckinkaid** [uataq/stilt#18]
Hi, complete newbie when it comes to R.  Ran:

if (!require('devtools')) install.packages('devtools')
devtools::install_github('benfasoli/uataq')

and after installing a slew of packages, I got this:  

* installing *source* package ‘uataq’ ...
** R
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘bindrcpp’

Could be user error on my end.  Also don't see a package named 'parallel' from a few of the CRAN source sites I looked at in the US.

Any help is appreciated with getting this up and running.  Trying to run some models to determine PM dispersion to help argue against a factory they are trying to build near by. 

-Thanks

**Comment by ckinkaid** [comment]
Nevermind, I'm an idiot.  I located those missing packages (there were 4 errors, bindrcpp, bindr, tidyselect, and purrr?) and now its installed fine.

**Comment by benfasoli** [comment]
Good to hear. Feel free to post another issue if you encounter other errors.
