### ISSUE TITLE
Alternative Projections for STILT footprints

### ISSUE THREAD

**Issue by taylorsjones** [uataq/stilt#3]
It would be nice to be able to save footprints in a variety of projections. My suggestion would be to use proj4 strings to define the projection. In the footprint configuration file, we can set the domain by defining the projection, the lower-left and upper-right corners, and the x and y resolution.

from foot_config.r:
```
#Footprint projection.
#Use proj4 convention ('http://proj4.org/faq.html') use '+proj=latlon' for latlon grid.
#projection <- '+proj=latlon'
projection <- '+proj=aea  +lat_0=48.128 +lon_0=11.575 +lat_1=40 +lat_2=60 +x_0=0 +y_0=0'
#Lower left and upper right corner lat and lon
ll_lon <- -73 #Degrees East
ur_lon <- -69.5
ll_lat <- 41.5   #Degrees North
ur_lat <- 43.5

#Resolution...match units with CRS! latlon: degrees, most other projections: meters
xres <- 1000
yres <- 1000
```
Then, in the code that calls the footprint maker, you convert all of the partcle lat/lon pairs to x/y in the projection before calling create_footprint. Note you will have to change the gaussian smoother to remove the latitude correction.

The trickiest part is getting the netCDF files CF compliant. It won't recognize the proj4 string, so in order to get it so that Panoply will correctly project it I made a clunky look up table (projection_dictionary.r) It also requires a bunch of other attributes.

I've attached my version of the footprint related files. Let me know how I can most effectively contribute. I don't want to make you sift through a bunch of peoples' poorly commented code!

[footprint_maker.zip](https://github.com/uataq/stilt/files/1900270/footprint_maker.zip)

**Comment by benfasoli** [comment]
Thanks for already putting so much time into this - a lot of the legwork looks like it's already done. I'd like to propose a couple small changes -

- Let's move the reprojection of the particle locations into `calc_footprint()`. This minimizes the amount of work that needs to happen between the PARTICLE.DAT output and `calc_footprint()` which should be helpful for users that don't want to buy into the whole R wrapper.
- It's probably best to refactor the code that [writes out the footprint](https://github.com/uataq/stilt/blob/38bf62f01fb0b9009631601cbf268c43b8dd5107/r/src/calc_footprint.r#L189-L256) and coerces the metadata into CF compliance as a separate function `write_footprint()` to reduce the complexity of `calc_footprint()`. We can then include the [crs to CF lookup table](http://cfconventions.org/wkt-proj-4.html) as well as any other CF-specific voodoo locally within that function.

Let me know if you see any substantial hurdles with going this route. I'll try to find some time to translate these thoughts into [develop](https://github.com/uataq/stilt/tree/develop) so we can do some testing.

**Comment by taylorsjones** [comment]
That all sounds great. I agree that `write_footprint()` and `calc_footprint()` should be different functions. 

I don't see any big hurdles, the only one would be how much time all of this is going to require of you...I imagine this is the 1st of many additional features we will try to add, so just let me know how I can best help.

**Comment by benfasoli** [comment]
It would be helpful if you could put together a list of which alternative projections (and associated example CF compliant metadata) we expect to be most utilized so that we can target the netCDF metadata tests most efficiently.

**Comment by taylorsjones** [comment]
I would suggest the following projections to start. These represent ones I have seen often in inventories and met fields used by Hysplit:

- Albers Conical Equal Area (aea)
- Lambert Conformal Conic (lcc)
- Polar Stereographic (ups)

Each of these have a name that is different for proj4 and CF:

| proj4 | CF |
|------|----|
| aea | albers_conical_equal_area |
| lcc | lambert_conformal_conic |
| ups | polar_stereographic |

In the netcdf file, there needs to be a variable called `Projection` and that variable must have an attribute called `grid_mapping_name` with the name of the projection as mentioned above.

There are a number of attributes used to define these projections. Here are the key ones.

| proj4 | CF |
|------|----|
| lat_0  | latitude_of_perspective_origin |
| lon_0 | longitude_of_perspective_origin |
| x_0 | false_easting |
|y_0 | false_northing |
| lat_1 | standard_parallel |
| lat_2 | standard_parallel |

In the netCDF file these need to be attributes of the variable `Projection` Note that if lat_1 and lat_2 values are given, then the `standard_parallel` attribute must be equal to a list of both values. This is all in the footprint maker I posted earlier.

Let me know what else you need.

**Comment by benfasoli** [comment]
Ok, the sample code was really helpful and I've made some progress. You can find a summary of the code changes at #8. The files are CF compliant and Panoply renders them properly.

Here's a quick test to ensure that an aea footprint projected back to lat/lon space agrees with the footprint gridded to lat/lon. The results agree closely enough that I'm happy to begin merging the branches. Let me know if there is anything I missed.

<img width="1005" alt="raster-projections" src="https://user-images.githubusercontent.com/12502924/39792769-2e645f98-52f7-11e8-9247-5debfaaeaea9.png">

**Comment by taylorsjones** [comment]
Hey Ben,

Are the x and y here long and lat? It looks like they are not in the same
location. Am I missing something?

Thanks,

Taylor

**Comment by taylorsjones** [comment]
Ok, great. I just read through your code changes, looks really nice. It's a shame we have to do the look-up tables and that CF conventions don't just use the proj4 string...but I think it's handled here as elegantly as possible. Thanks for doing this!

**Comment by benfasoli** [comment]
As elegant as a lookup table can be...
