### ISSUE TITLE
Bugs Report

### ISSUE THREAD

**Issue by ddlddl58** [uataq/stilt#35]
Hi developers,

    When I learn your WBB tutorial, all is OK, except for the html out step.
    It hints the following information.

Loading required namespace: ncdf4
Warning message:
`data_frame()` is deprecated, use `tibble()`.
This warning is displayed once per session.
Error in htmlwidgets::saveWidget(p, "timeseries.html") :
  Saving a widget with selfcontained = TRUE requires pandoc. For details see:
https://github.com/rstudio/rmarkdown/blob/master/PANDOC.md
Execution halted

Regards,

ddlddl58

**Comment by benfasoli** [comment]
Thanks for posting - I [updated the tutorial](https://github.com/uataq/stilt-tutorials/commit/7718de541329522b158a4fb42133c5a9a64dced7) to remove the deprecation warning. For the html output, [installing pandoc](https://pandoc.org/installing.html) will fix the error.

Alternatively, you can add modify the [last line of the tutorial code](https://github.com/uataq/stilt-tutorials/blob/master/01-wbb/tutorial.r#L126) to disable the use of pandoc -

```r
htmlwidgets::saveWidget(map, 'average_contribution.html', selfcontained = F)
```

This will output `average_contribution.html` as well as a separate directory of dependency files for the mapping library.
