### ISSUE TITLE
Metrological Grid Nesting does not work

### ISSUE THREAD

**Issue by sajjanh2** [uataq/stilt#39]
Hi the hymodelc binary built for Centos does not seem to allow for meteorological grid nesting. Instead of transitioning to using the meteorology from a lower resolution file at the boundary of a high resolution file the trajectories stop at the high resolution boundary. This feature is available in the hymodelc binary in the AER's STILT distribution and seems to be in Hysplit. In those cases the trajectories transition to using the lower resolution file at the boundary of the high resolution one.  Is this a bug with UATAQ's stilt distribution?

**Comment by benfasoli** [comment]
Looks like this was an upstream issue from the BGC Jena fortran code (trunk) that has been fixed. #40 updates the precompiled binaries and it seems to have resolved the issue on my side. You'll need to start a new STILT project to fetch the update, or `git pull` and rerun the `./setup` script from your existing STILT directory.
