### ISSUE TITLE
proj_as_proj_string: Cannot find proj.db

### ISSUE THREAD

**Issue by ankitpatel0698** [uataq/stilt#67]
Why this error is coming though i am getting output netcdf file?
proj_as_proj_string: Cannot find proj.db
proj_as_wkt: Cannot find proj.db
proj_create: Cannot find proj.db
proj_as_wkt: Cannot find proj.db
![Screenshot from 2021-04-08 13-28-30](https://user-images.githubusercontent.com/75941016/113990752-677d7880-986f-11eb-8d87-c04a4e00503a.png)

& Also Please tell the role of number of receptors. How should i decide that it should be 1 or 10 or more? 
Thanks.

**Comment by benfasoli** [comment]
@ankitpatel0698 has this issue been resolved?

**Comment by ankitpatel0698** [comment]
> @ankitpatel0698 has this issue been resolved?

Yes sir, this issue was resolved. Thanks
