### ISSUE TITLE
plotting trajectories using .netcdf outputs

### ISSUE THREAD

**Issue by inku0120** [uataq/stilt#70]
Hii sir
Thanks for the wonderful tutorials you have uploaded. I was able to install and run the model successfully. I have got the outputs. I am interested to plot the trajectories (i.e. only path trajectory) using these outputs like as follows:
![hys (1)](https://user-images.githubusercontent.com/84829143/120697999-0fa86a00-c4cc-11eb-820a-890fea4ac9ca.png)
But since it has footprints i am getting an output like this 
![filename](https://user-images.githubusercontent.com/84829143/120698447-b5f46f80-c4cc-11eb-8723-18333be41bad.gif)

So, can you please help me how i can be able to plot trajectories only using STILT outputs.

**Comment by benfasoli** [comment]
The time resolved trajectory locations can be found in the `<simulation_id>_traj.rds` file output for each of your simulations. Try loading the trajectory data using `readRDS`, following the [documentation for STILT's output files](https://uataq.github.io/stilt/#/output-files?id=particle-trajectories) -

```r
traj <- readRDS('<simulation_id>_traj.rds')
str(traj)
# List of 4
# $ file    : chr "<stilt_wd>/out/by-id/<simulation_id>/<simulation_id>_traj.rds
# $ receptor:List of 4
# ..$ run_time: POSIXct[1:1], format: "1983-09-18 21:00:00"
# ..$ lati    : num 39.6
# ..$ long    : num -80.4
# ..$ zagl    : num 10
# $ particle:Classes ‘tbl_df’, ‘tbl’ and 'data.frame':    11712136 obs. of  12 variables:
# ..$ time                : num [1:11712136] -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...
# ..$ indx                : num [1:11712136] 1 2 3 4 5 6 7 8 9 10 ...
# ..$ long                : num [1:11712136] -80.4 -80.4 -80.4 -80.4 -80.4 ...
# ..$ lati                : num [1:11712136] 39.6 39.6 39.6 39.6 39.6 ...
# ..$ zagl                : num [1:11712136] 5.63 41.37 30.95 3.32 28.88 ...
# ..$ foot                : num [1:11712136] 0.0626 0.043 0.043 0.0626 0.0627 ...
# ..$ mlht                : num [1:11712136] 1459 1459 1459 1459 1459 ...
# ..$ dens                : num [1:11712136] 1.1 1.1 1.1 1.1 1.1 ...
# ..$ samt                : num [1:11712136] 1 1 1 1 1 1 1 1 1 1 ...
# ..$ sigw                : num [1:11712136] 1.08 1.09 1.09 1.08 1.08 ...
# ..$ tlgr                : num [1:11712136] 1.67 4.98 4.98 1.67 1.67 ...
# ..$ foot_no_hnf_dilution: num [1:11712136] 0.00224 0.00224 0.00224 0.00224 0.00224 ...
```

You can use `traj$particle` to produce visualizations of the particle-level data. `traj$particle$time` is given in minutes relative to `traj$receptor$run_time`.
