### ISSUE TITLE
Error linking Homebrew gfortran installation in hycs_std (?)

### ISSUE THREAD

**Issue by BlueGrisGris** [uataq/stilt#78]
When I try to run a tutorial example it returns the following shell abort message and R warning for each receptor.  No output files (footprints etc) are produced.

```
sh: line 1:  3156 Abort trap: 6           ./hycs_std >> stilt.log 2>&1
Warning message:
In calc_trajectory(namelist, rundir, emisshrs, hnf_plume, met_files,  :
  Failed to output  /Users/ethan/Desktop/research/phd/em27/wbb-tutorial/out/by-id/201512100000_-111.847672_40.766189_25/PARTICLE_STILT.DAT
```

I have not been able to follow the source of the error.

I am running on Mac OS 10.14.16, R version 4.1.2, gfortran from Homebrew gcc 11.2.0_1.

I hope this is an appropriate venue to ask about this.

Thanks!

UPDATE----

I found the stilt.log file, and it said:

```
dyld: Library not loaded: /usr/local/gfortran/lib/libgfortran.5.dylib
  Referenced from: /Users/ethan/Desktop/research/phd/em27/wbb-tutorial/out/by-id/201512100000_-111.847672_40.766189_25/./hycs_std
  Reason: no suitable image found.  Did find:
	/usr/local/lib/libgfortran.5.dylib: stat() failed with errno=62
Failed to output  /Users/ethan/Desktop/research/phd/em27/wbb-tutorial/out/by-id/201512100000_-111.847672_40.766189_25/PARTICLE_STILT.DAT 

```
This seems to have to do with an earlier issue I had while running stilt_init(), which would result in this error when compiling:

```
Compiling footprint kernel aggregation subroutine...
gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c  r/src/permute.f90 -o r/src/permute.o
clang -mmacosx-version-min=10.13 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o r/src/permute.so r/src/permute.o -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0'
ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [r/src/permute.so] Error 1
```

I fixed this issue with the solution at this stackexchange answer about another R package (Rccp) having issues linking Homebrew installations of gfortran:
https://stackoverflow.com/questions/29992066/rcpp-warning-directory-not-found-for-option-l-usr-local-cellar-gfortran-4-8/29993906#29993906

I fixed the original error from hycs_std by linking libgfortran.X.dylib to where it says it wants it in stilt.log

I also had to link the library libquadmath.X.dylib

Everything seems to be working now!

It seems there is a widespread hard time to be had finding Homebrew installations of gfortran.

**Comment by tartanrunner25** [comment]
Glad you were able to fix the issue. I am assuming there are no other issues so I am closing this out.
