### ISSUE TITLE
problems with wrf-stilt

### ISSUE THREAD

**Issue by cristianarango2** [uataq/stilt#86]
Hi,

I am running the STILT tutorial with wrf data (the wrfout in the tutorial folder) and I am getting the following error:
 Using an existing decoding configuration: WRFDATA.CFG
 NetCDF: Variable not found
 ZNT
 Variable not found: ZNT
 Some defined variables not found in file.

Thank you for your help!
Best regards, Cristian Arango

**Comment by tartanrunner25** [comment]
Hi Christian,

Unfortunately, I am unable to replicate this issue, even when running the code with the tutorial files. How are you running the code. For example, when you run the converter how is it being executed?

-Derek
