### ISSUE TITLE
stilt

### ISSUE THREAD

**Issue by XIR-art** [uataq/stilt#93]
HI!
 1、 Can I use stilt mode to simulate the concentration between altitude layers, for example, simulating the concentration at 40~50m in a site area?
2、Does the stilt model provide a calculation of the background CO2 concentration?

**Comment by tartanrunner25** [comment]
1) STILT can compute CO2 at different levels, the receptor height just has to be changed. 
2) Some studies just use a background site to estimate CO2 while others have interpolated STILT trajectory end points to some type of 3D CO2 product like CarbonTracker. There’s no code code available that does this, so you will need to write your own R code to do this.

I really suggest you read the STILT literature as there is already lot out there that can answer your questions.
