### ISSUE TITLE
emission.rds file 

### ISSUE THREAD

**Issue by XIR-art** [uataq/stilt#94]
Hello, sorry to bother you, is the script for creating the in your tutorial.r there? I am using this program to read my emission nc file and I have the following problem, can you please help me， thank you for your precious time, thank you very much.
[Uploading codefile.rar…]()

1. non-numeric argument to binary operator
2. 'subset' must be logical
I can't upload my code file, can you contact me?
 thank you very much.

**Comment by tartanrunner25** [comment]
Hi XIR,

Unfortunately,  you will need to troubleshoot your owns scripts. We simply provide the code needed to run STILT, and to produce STILT related output (i.e footprints, trajectories). The script we provided in the tutorial only works the tutorial rds emission file. Therefore, you will need to rewrite exiting code and/or develop your owns script that is compatible with the format of your .nc emission file. The error you are providing makes me suspect that there is an issue with how you are subsetting your arrays, but its difficult to say much more without seeing the code.
